### ISSUE TITLE
Jura exposure_tables overrides for missing darks

### ISSUE THREAD

**Issue by sbailey** [desihub/desispec#2255]
Creating a non-code ticket to document what I did for Jura:

Nights 20210106, 20210314, 20210519, 20230309, 20231220 and thus needed an override file entry to link the badcolumns files.

Symptom:
```
NIGHT=20210106
desi_proc_night -n $NIGHT --dry-run-level 3
--> "Exiting because not all calibration files accounted for with links or submissions"
```
Fix:
```
desi_create_override_file -n $NIGHT --no-ff-solve-grad
--> previous night as reference night, yes to everything except darks
```

Result:
exposure_tables/202101/override_20210106.yaml created with:
```
# DESI override file for 20210106
# linkcal notes: current night's bias,cte flats,psfs,flats were ok; badcols were bad

calibration:
  linkcal:
    include: badcolumns
    refnight: 20210105
```

Previous test passes:
```
desi_proc_night -n $NIGHT --dry-run-level 3
--> All done: Completed submission of exposures for night 20210106
```

I did this for nights 20210106, 20210314, 20210519, 20230309.
Night 20231220 was handled somewhat differently since its ref night is 20231217 (no data on 1218 or 1219) and it already had an override file for --autocal-ff-solve-grad, so its override file was augmented instead of created anew.

I committed these to exposure_tables svn.
